### PR TITLE
Feature/directoryservice

### PR DESCRIPTION
**Pull request by tomvachon**
Delete Directory Service Directories

### CODE REVIEW

**Comment by svenwltr** [comment]
This one doesn't work for me. It looks like it somehow ignores the region (see hostnames in debug output).

```
$ aws clouddirectory list-directories
{
    "Directories": [
        {
            "State": "ENABLED", 
            "CreationDateTime": 1520325250.996, 
            "Name": "foobar", 
            "DirectoryArn": "arn:aws:clouddirectory:eu-west-1:999999999999:directory/AbUJBm-9zE9FqabcdePeIx8"
        }
    ]
}
```

Debug output:

```
DEBU[0003] sending AWS request:
    > POST / HTTP/1.1
    > Host: ds.eu-west-1.amazonaws.com
    > Authorization: <hidden>
    > Content-Length: 13
    > Content-Type: application/x-amz-json-1.1
    > User-Agent: aws-sdk-go/1.13.8 (go1.9.2; linux; amd64)
    > X-Amz-Date: 20180306T083555Z
    > X-Amz-Target: DirectoryService_20150416.DescribeDirectories
    > 
    > {"Limit":100} 
DEBU[0003] received AWS response:
    < HTTP/1.1 200 OK
    < Content-Length: 28
    < Content-Type: application/x-amz-json-1.1
    < Date: Tue, 06 Mar 2018 08:35:55 GMT
    < X-Amzn-Requestid: 62fa2653-2119-11e8-9864-97f51312f012
    < 
    < {"DirectoryDescriptions":[]} 
DEBU[0003] sending AWS request:
    > POST / HTTP/1.1
    > Host: ds.us-east-1.amazonaws.com
    > Authorization: <hidden>
    > Content-Length: 13
    > Content-Type: application/x-amz-json-1.1
    > User-Agent: aws-sdk-go/1.13.8 (go1.9.2; linux; amd64)
    > X-Amz-Date: 20180306T083555Z
    > X-Amz-Target: DirectoryService_20150416.DescribeDirectories
    > 
    > {"Limit":100} 
DEBU[0004] received AWS response:
    < HTTP/1.1 200 OK
    < Content-Length: 28
    < Content-Type: application/x-amz-json-1.1
    < Date: Tue, 06 Mar 2018 08:35:55 GMT
    < X-Amzn-Requestid: 63386792-2119-11e8-afa7-1b8ba2367686
    < 
    < {"DirectoryDescriptions":[]} 
Scan complete: 0 total, 0 nukeable, 0 filtered.

No resource to delete.
```

**Comment by tomvachon** [comment]
That is odd. I’ll look at it

**Comment by tomvachon** [comment]
@svenwltr You were testing CloudDirectory which isnt the same thing as DirectoryService (even though they are in the same console pane).

DirectoryService is Managed MS AD or SimpleAD (Samba4).  CloudDirectory is what you are looking for.  That PR was just filed.  To test this you want to use: https://console.aws.amazon.com/directoryservice/home?region=us-east-1#CreateDomainWizardPlace:Simple%20AD

**Comment by svenwltr** [comment]
Ah I see. It looks like I just got too used to the inconsistent naming on AWS.

**Pull request merged**
