### PR TITLE
feat: revenant

### LINKED ISSUE #500: CloudWatchLogsLogGroup - stuck waiting
```
/aws/eks/idx-eks-pulumi-test-eksCluster-6586a80/cluster - waiting Removal requested: 1 waiting, 0 failed, 74 skipped, 95 finished 
us-east-2 - CloudWatchLogsLogGroup - /aws/eks/idx-eks-pulumi-test-eksCluster-6586a80/cluster - waiting Removal requested: 1 waiting, 0 failed, 74 skipped, 95 finished
```
Not sure what to add, but I able to delete this log group manually

### PR DESCRIPTION
**Pull request by github-vincent-miszczak**
Fixes https://github.com/rebuy-de/aws-nuke/issues/500
We have this issue with our EKS clusters, `nuke` never completes.

Resources may come back after `Remove()` because they are managed by other resources that may be removed later (that's the case with EKS and log groups).

I added the opportunity to mark such resources to handle them correctly.

### CODE REVIEW

**Comment by tudrzal** [comment]
Hi, we have the same issue, could this make it into incoming release please?

**Comment by TomasMocek** [comment]
Hello, perhaps @bjoernhaeuser can have a look?

**Comment by bdellegrazie** [comment]
@github-vincent-miszczak could you rebase this please?
@bjoernhaeuser / @TomasMocek once rebased, any chance of a review and merge please?

**Comment by ekristen** [comment]
I like this idea, however I need to research and understand this a bit better before implementing in libnuke and aws-nuke@v3 as such I've opened an issue for tracking purposes https://github.com/ekristen/libnuke/issues/75

If you still feel this is an issue and should be implemented, please comment over there.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Pull request closed without merging**
