### PR TITLE
Adapt Readme & CI for main branch

### PR DESCRIPTION
**Pull request by der-eismann**
Follow up to #595

/cc @dfreudenberger

### CODE REVIEW

**Comment by svenwltr** [comment]
Do we break things like forked repos with this?

**Comment by der-eismann** [comment]
I'd say it is the downstream's task to keep up with our changes, especially if it's such a rare occasion like a main branch change.

**Review by svenwltr — APPROVED** [review]

**Comment by bjoernhaeuser** [comment]
> Do we break things like forked repos with this?

We do not. We only break everyone who is pulling "master". Is GitHub handling this for us? I do not expect it todo. We should probably delete the master branch and make every PR we have right now point to main afterwards.

**Comment by der-eismann** [comment]
GitHub is actually handling this.
screenshot
But yeah, people pulling `master` from quay will have problems.

**Review by bjoernhaeuser — APPROVED** [review]

**Pull request merged**
