### PR TITLE
fix: update module version to v2

### PR DESCRIPTION
**Pull request by kazimierzbudzyk**
Fixes module versioning to allow aws-nuke to be used as library.

Ref: https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

### CODE REVIEW

**Comment by Wojtek-ana** [comment]
I am curious about the progress of this pull request, need it for a project. Is there anything I can do to help?

**Comment by kazimierzbudzyk** [comment]
@Wojtek-ana feel free to make any contributions! I didn't have much tractions with feedback on the issue or the PR, the state is basically as you see it here. I am unblocked by forking and vendroing that, but very much would like to switch back to upstream.

**Comment by svenwltr** [comment]
Hello. Merging this took a bit longer, because we had to discuss it internally.

Please be cautious when using aws-nuke as a library, because it is not built as a library and there are not guarantees for api stability at all.

**Comment by tbuatois** [comment]
Nice work guys, have you an ETA on a new release with this PR ? We still cannot import aws-nuke as module since it needs a github release... 
Thanks a lot

**Comment by gowtham570** [comment]
+1 Would like to know the ETA on new release for this changes to be able to use aws-nuke as a module. TIA

**Comment by gowtham570** [comment]
Thanks @svenwltr for releasing the latest version `2.19.0` with the above changes. I was able to import the aws-nuke as a module with the latest release.

**Pull request merged**
