### PR TITLE
Adds additional AWS IoT considerations for deletion

### PR DESCRIPTION
**Pull request by richardneililagan**
This PR addresses the points detailed in #374. 

Changes:
- Now detaches attached principals to IoT things prior to deletion
- Now detaches attached targets to IoT policies prior to deletion
- Now deprecates non-default versions of IoT policies prior to deletion
- Now deactivates IoT certificates prior to deletion

### CODE REVIEW

**Comment by timboven** [comment]
Just tested this one out as I had the same issue and this seemed to work fine

**Comment by svenwltr** [comment]
Hello and sorry to the delay.

I think it would be more clean to exclude those resources within the filter function. See [EC2 Instance](https://github.com/rebuy-de/aws-nuke/blob/08e6b8313b510f7d43fe5b45a090ed48c98bfc6a/resources/ec2-instances.go#L42-L47) for an example.

The reason for doing so is to give the user a proper expectation what resources exist and what *aws-nuke* is doing with them in the initial resource listing.

**Comment by richardneililagan** [comment]
@svenwltr Apologies --- have been away for some R&R.

I'd appreciate it if you could expound on that more --- there's essentially no hard filtering involved in the PR; really more of just additional processing for some resources, but in the end, the resources still get nuked.

**Comment by svenwltr** [comment]
@richardneililagan You are right. Thanks for your patience.

**Pull request merged**
