### PR TITLE
Upgrade aws-sdk-go to latest version

### LINKED ISSUE #397: AWS nuke not working with credential_process + source_profile + role_arn combination
# Expected Behaviour

Given config:

```ini
[profile test]
region = us-west-2
credential_process = cat ./cred.json

[profile testnoassume]
source_profile = test

[profile testassume]
source_profile = test
role_arn = arn:aws:iam::222222222222:role/OrganizationAccountAccessRole
```

When:
* executing aws-nuke with profile `testassume` or `testnoassume`

Then:
* aws-nuke should connect to aws properly.

# Actual Behaviour

aws-nuke fails the following commands:
```
$ aws-nuke --config config.yaml --profile testassume
Error: failed to create default session in us-east-1: SharedConfigAssumeRoleError: failed to load assume role for arn:aws:iam::222222222222:role/OrganizationAccountAccessRole, source profile has no shared credentials
```
and
```
$ aws-nuke --config config.yaml --profile testnoassume
Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

# Additional Context

https://docs.aws.amazon.com/cli/latest/topic/config-vars.html#sourcing-credentials-from-external-processes

Very similar issue:
https://github.com/hashicorp/packer/issues/7142#issuecomment-511016332

Looks like this could be an SDK issue, so upgrading to the latest go sdk might solve this.

### PR DESCRIPTION
**Pull request by reegnz**
Fixes #397

### CODE REVIEW

**Comment by reegnz** [comment]
I verified that this upgrade fixes #397.

**Comment by svenwltr** [comment]
Thank you!

**Comment by adamcousins** [comment]
@svenwltr 
Is it possible this change can get cut into a new minor release?

I'm testing assume-role logic with attempt to resolve a session token expiry issue.

**Comment by svenwltr** [comment]
@adamcousins Sure, it was way overdue anyways: https://github.com/rebuy-de/aws-nuke/releases/tag/v2.12.0

**Comment by yi2020** [comment]
@svenwltr trying aws-nuke with aws-vault now and hitting the same issue as 397. Before I open a new issue, can you confirm I'm going about this the right way? Using both the "latest" version and specifically v2.12.0:

```
% aws-vault exec someprofile --duration=8h -- docker run \
    --rm -it \
    -v /Users/acme/nuke-config.yml:/home/aws-nuke/config.yml \
    quay.io/rebuy/aws-nuke:latest \
    --config /home/aws-nuke/config.yml --profile Default -v
DEBU[0000] creating new session in us-east-1 for        
DEBU[0000] creating new root session in us-east-1       
Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
% aws-vault exec someprofile --duration=8h -- docker run \
    --rm -it \
    -v /Users/acme/nuke-config.yml:/home/aws-nuke/config.yml \
    quay.io/rebuy/aws-nuke:v2.12.0 \
    --config /home/aws-nuke/config.yml --profile Default  
Unable to find image 'quay.io/rebuy/aws-nuke:v2.12.0' locally
v2.12.0: Pulling from rebuy/aws-nuke
9d48c3bd43c5: Pull complete 
c33def6e5f4b: Pull complete 
69ccab98a7b0: Pull complete 
20729c275acf: Pull complete 
Digest: sha256:abdb516cb71667c3f32321a90f44fae2de53e75e15bd96f5d143ca414a6a07fc
Status: Downloaded newer image for quay.io/rebuy/aws-nuke:v2.12.0
Error: failed get caller identity: NoCredentialProviders: no valid providers in chain. Deprecated.
	For verbose messaging see aws.Config.CredentialsChainVerboseErrors
```

**Comment by svenwltr** [comment]
@yi2020 Please open a ticket anyways. Otherwise it gets hard to manage issues.

**Pull request merged**
