### PR TITLE
use blocklist over blacklist

### PR DESCRIPTION
**Pull request by dfreudenberger**
addresses #594

### CODE REVIEW

**Comment by svenwltr** [comment]
The problem is that this is a breaking change for all users. So either it causes a major release or we have to deprecate the old term and make both ones work for a while in parallel.

**Comment by der-eismann** [comment]
Let's move from master to main in the same step and do a major release then

**Comment by dfreudenberger** [comment]
Let me do the required changes in order to be backwards compatible. I think we shouldn't break compatibility if it's easy to avoid.

**Review by scottschreckengaust — DISMISSED** [review]
Simple change, looks good.

**Comment by scottschreckengaust** [comment]
> The problem is that this is a breaking change for all users. So either it causes a major release or we have to deprecate the old term and make both ones work for a while in parallel.

Good point to deprecate.

**Comment by scottschreckengaust** [comment]
> Let's move from master to main in the same step and do a major release then

Bonus ;-)

**Review by svenwltr — DISMISSED** [review]

**Review by der-eismann — DISMISSED** [review]

**Review by svenwltr — APPROVED** [review]

**Review by der-eismann — APPROVED** [review]

**Pull request merged**
