### PR TITLE
Baseline filter generation

### PR DESCRIPTION
**Pull request by dooreelko**
Pretty much implementing https://github.com/rebuy-de/aws-nuke/issues/292

A new command "baseline" which will print yaml-ready resource filters (based on names or properties).

### CODE REVIEW

**Comment by svenwltr** [comment]
Hello @dooreelko,

thank you for your contribution and sorry for the late response. I have two thoughts on this:

1. There is no documentation, so we should add something to the README.
2. Currently, it simply loops over all properties of an resource and adds each one to the config. This can render the output of some resources useless, because those filters are not grouped. An example are S3 objects, where it would basically filter all objects that are not versioned:

```yaml
S3Object:
- property: "Key" 
  value: "my-s3-file"
- property: "VersionID" 
  value: "null"
- property: "IsLatest" 
  value: "true"
- property: "Bucket" 
  value: "some-bucket"
```

That does not sound like the desired behavior to me. What do you think?

**Comment by dooreelko** [comment]
Hi @svenwltr,

I've added docs on the command, please have a look.
As for the second point, i'm not sure i understand completely. From the baseline perspective, we can only offer providing individual filters for each discovered resources. And based on my undersaanding of how the nuke processes filters, first filter wins, so i don't think there's a way to implement custom filter grouping by autogeneration.

**Comment by svenwltr** [comment]
Hello. Sorry for the very late answer.

> And based on my undersaanding of how the nuke processes filters, first filter wins, so i don't think there's a way to implement custom filter grouping by autogeneration.

I guess that is the reason we did not implement it yet. This solution feels a bit non-intuitive to me, because the result looks random to me. Does @rebuy-de/prp-aws-nuke have an opinion on this?

**Comment by bjoernhaeuser** [comment]
I think this command would really help users. Not sure how to remove the randomness though.

**Comment by ekristen** [comment]
@dooreelko I love the idea, but since the fork has diverged so much I cannot pull this directly over. I've opened an issue to track this and will look more into this. There are other requests for config validation which might play nicely into this as well. https://github.com/ekristen/aws-nuke/issues/361

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Comment by dooreelko** [comment]
Dude, it's been four years. I don't think I have enough motivation to pick this up :)

**Comment by ekristen** [comment]
Totally understand. I had no control over this until recently. I am looking at a feature like this for the fork. If you want to contribute there, please do, if not I totally understand. Cheers.

**Pull request closed without merging**
