### PR TITLE
Add deletion protection support for RDS

### PR DESCRIPTION
**Pull request by sas-pemcne**
This will disable deletion protection on RDS instances and clusters before removal. No extra calls are being made since the DeletionProtection boolean is being returned with the describe api call. Boolean is being stored in the struct under DeletionProtection and queried during removal of the resource. Instance or cluster is modified only if needed to avoid any extra api calls.

### CODE REVIEW

**Comment by sas-pemcne** [comment]
Ah, this depends on aws-sdk-go [v1.15.43](https://github.com/aws/aws-sdk-go/releases/tag/v1.15.43). Glide/Travis looks to be pulling the minimum of v1.14.9. 

From the release notes of v1.15.43:

> service/rds: Updates service API and documentation
> This release includes Deletion Protection for RDS databases.

**Comment by svenwltr** [comment]
@sas-pemcne I updated the SDK in #307. Please rebase your branch.

**Comment by svenwltr** [comment]
Hello @sas-pemcne. I am not sure how this happened, but this PR contains now a lot of unrelated commits. Also it contains the actually relevant commit "Add deletion protection support for RDS" even twice (ae8b4eb2825e1db27d9693cd8d658289218c3f1d, b88b0e5ddc395b1915e42a7fece1ec0e05309366).

This confuses me a bit.

**Comment by sas-pemcne** [comment]
That's weird, I'll clean it up.

**Comment by sas-pemcne** [comment]
I rebased the branch and cleaned everything up.

**Comment by svenwltr** [comment]
Great. Thank you!

**Pull request merged**
