### PR TITLE
Add --max-wait-retries flag to bail out early if the script is stuck waiting

### PR DESCRIPTION
**Pull request by scottybrisbane**
We want to get to a point where we can run `aws-nuke` through our CI/CD platform and have noticed that it can get stuck in a waiting state for a considerable length of time in some scenarios. 

This pull request aims to resolve that by adding a flag that, if set, will cause the program to bail out if it is waiting for `n` number of iterations and no new work has been discovered in that time.

### CODE REVIEW

**Comment by svenwltr** [comment]
Hello @scottybrisbane,

can you elaborate in what cases a resource stucks in `Waiting` state? This sounds like there is a bug in one of our resources.

**Comment by scottybrisbane** [comment]
Hi @svenwltr, the primary case in which something was truly 'stuck' was a CloudFormation stack that had gotten into a nasty state with all resources it managed having already been deleted. It got confused by this and refused to delete, causing aws-nuke to keep that resource in a waiting state. The other case was in deleting an ElasticSearch Domain, which can take a considerable amount of time. It wasn't really 'stuck' as such, but would have left aws-nuke in a waiting loop for a considerable amount of time whilst it was being deleted.

I haven't experienced it myself, but a colleague mentioned that they also had an issue with an OpsWorks stack in which aws-nuke entered a loop as it couldn't properly delete the resources.

**Comment by svenwltr** [comment]
I see. We already fixed the CloudFormation stack.

I think we could merge this PR, but it is essentially just a workaround for bugs.

@rebuy-de/prp-aws-nuke Please review.

**Comment by scottybrisbane** [comment]
Thanks for the reviews!

@svenwltr I do agree that it's essentially just a workaround for bugs, but it should better enable us (and others) to run the tool from our CI/CD platform, without fear of the program entering a long-running loop.

**Pull request merged**
