### PR TITLE
Add Force flag to CW events rule deletion

### PR DESCRIPTION
**Pull request by nimrodkor**
Resolves https://github.com/rebuy-de/aws-nuke/issues/448

### CODE REVIEW

**Comment by svenwltr** [comment]
Hey @nimrodkor, the tests fail. It looks like you have to use [`aws.Bool`](https://docs.aws.amazon.com/sdk-for-go/api/aws/#Bool).

**Comment by nimrodkor** [comment]
Hey @svenwltr, thanks! Fixed it, build now passes

**Comment by svenwltr** [comment]
Could you please also squash your commits? See [CONTRIBUTING.md](https://github.com/rebuy-de/aws-nuke/blob/8ca9253/CONTRIBUTING.md#squash).

**Comment by nimrodkor** [comment]
@svenwltr Can't say it's too easy to do as requested, but it's done.
By the way - you can always squash the PR commits when merging it, so what's the point of requiring a one commit PR? Especially when demanding the PR stays updated with master...

**Comment by svenwltr** [comment]
Thanks @nimrodkor.

Here is the section from the [contribution guidelines](https://github.com/rebuy-de/aws-nuke/blob/8ca9253/CONTRIBUTING.md#rebase):

> **Note:** We cannot use the GitHub Squash Merge, since it would alter the commit author. We do not want this, because it would not properly acknowledge the contributions of the community.

Do you think this is not a valid reason for not GitHub squash feature?

**Comment by nimrodkor** [comment]
@svenwltr when you squash and merge using github, it does save all the contributors that contributed - so it doesn't completely ruin the history. it's not a perfect world, but I'd rather have an easier time merging than having to work so hard for every comment fix and get the correct credit.

**Comment by svenwltr** [comment]
@nimrodkor FYI: We simplified the contribution guidelines and will squash all PRs from now on. See https://github.com/rebuy-de/aws-nuke/pull/461.

**Pull request merged**
