### PR TITLE
Filter main route tables

### PR DESCRIPTION
**Pull request by leighpascoe**
Description

AWS does not allow you to delete main route tables, see [AWS docs](https://docs.aws.amazon.com/vpc/latest/userguide/WorkWithRouteTables.html#DeleteRouteTable). 
Aws-nuke wants to delete a VPC, it expects the main route table to be deleted first, the main route table cannot be deleted, therefore the VPC fails to delete due to a dependency error.

Proposed Solution
After Describing the route tables, check for any `Associations` where `Main` is `true`. There may be zero to many Associations. If at least one `main` Association is found on the Toute Table, then the Route Table will will not be added to the returned collection of Route Tables

I have tested this on VPC with just a main route table, as well as VPC's with multiple route tables.

Related Issues: https://github.com/rebuy-de/aws-nuke/issues/946 https://github.com/rebuy-de/aws-nuke/issues/785

### CODE REVIEW

**Comment by der-eismann** [comment]
Hey @leighpascoe, sorry for the late reply. We already have a dedicated `Filter()` function for these things, see [this](https://github.com/rebuy-de/aws-nuke/blob/main/resources/ec2-instances.go#L61-L66) for example. Would be great if you could use this instead of your solution.

**Comment by leighpascoe** [comment]
@der-eismann I've made the update, and tested it. Ready for re-review

**Comment by leighpascoe** [comment]
@svenwltr and @der-eismann Could I please get this re-reviewed. We are looking forward to using the released container instead of building our own forked image

**Comment by leighpascoe** [comment]
@svenwltr, Am I missing anything in this PR?

**Comment by leighpascoe** [comment]
@der-eismann  We have been using aws-nuke on this custom branch for the last 4 months to delete VPC, it's well tested. Could we please get this reviewed and merged?

**Review by der-eismann — APPROVED** [review]

**Review by bjoernhaeuser — APPROVED** [review]

**Pull request merged**
