### PR TITLE
Force Remove Lightsail instances

### PR DESCRIPTION
**Pull request by jakubincloud**
Change to add ForceDeleteAddOns: True parameter when deleting Lightsail instances.

### CODE REVIEW

**Review by der-eismann — APPROVED** [review]

**Comment by bjoernhaeuser** [comment]
@rebuy-de/prp-aws-nuke should this feature moved behind a feature flag?

**Comment by svenwltr** [comment]
> @rebuy-de/prp-aws-nuke should this feature moved behind a feature flag?

I vote for yes.

**Comment by bjoernhaeuser** [comment]
@jakubincloud sorry for the late response. We recently introduced feature-flags, to enable "deleting protected resources". Please take a look at the current config and move that feature behind a new flag.

Please let us know if we can help, thank you! :)

**Comment by der-eismann** [comment]
Replaced by #597

**Pull request closed without merging**
