### PR TITLE
Allow nuking of SAML and OpenIdConnect Identity Provider

### PR DESCRIPTION
**Pull request by kinitic**
Added the capability to nuke specific SAML and OpenIdConnect Identity Providers.

This has been tested using ADFS within our test infrastructure.

### CODE REVIEW

**Comment by asehra** [comment]
Is this ready to be merged?

**Comment by svenwltr** [comment]
@asehra Sorry for the late response.

I am a bit confused about your commit. Why are there three people involved?

**Comment by asehra** [comment]
@svenwltr No worries. I was butting in because i am eager to use this functionality. Pretty Please. 😃 

Commit has 2 authors because they might have used something like [git-duet](https://github.com/git-duet/git-duet)

**Comment by kinitic** [comment]
Hi @svenwltr, just to provide some clarify the commit. I was collaborating with Celeste Phutela on this piece of work and created the PR on her behalf. Would it be possible to merge the changes in?

**Pull request merged**
