### PR TITLE
disable cloudfront distribution before delete it

### LINKED ISSUE #571: CloudFront distribution needs to be disabled
I try to reopen the issue #325 

in version 2.14.0 

```
version:     v2.14.0
build date:  Thu Jan 30 13:57:34 UTC 2020
scm hash:    d9bff8695c3a3e8f72050a76f14ce3f05c07b5c6
environment: root@3bab39a3ac52
```

the nuke command fails with

```
ERRO[0276] There are resources in failed state, but none are ready for deletion, anymore. 

global - CloudFrontDistribution - EJ8POXXXXXXXX - failed
ERRO[0276] DistributionNotDisabled: The distribution you are trying to delete has not been disabled.
        status code: 409, request id: 521b837d-XXXX-XXXX-XXXX-XXXXXXXXXXXX 
global - CloudFrontDistributionDeployment - EJ8POXXXXXXXX - failed
ERRO[0276] IllegalUpdate: You cannot update the specified distribution using this API version because it is associated with a cache policy.
        status code: 400, request id: d7f83e17-XXXX-XXXX-XXXX-XXXXXXXXXXXX 
```

Maybe also because the new cache policy mechanism?

_Originally posted by @wdalmut in https://github.com/rebuy-de/aws-nuke/issues/325#issuecomment-725609960_

### PR DESCRIPTION
**Pull request by wdalmut**
This PR closes #571 

It updates the cloudfront distribution status and waits until the distribution is in the "deployed" status

### CODE REVIEW

**Review by svenwltr — CHANGES_REQUESTED** [review]
Hello.

`WaitUntilDistributionDeployed` looks like a blocking call. *aws-nuke* works with a fast feedback loop to not block other resources while deleting.

The right way to handle this is to check whether the Distribution is deployed and return an `error` if so. *aws-nuke* will retry to remove it later.

**Comment by wdalmut** [comment]
ok,

i try to return back an error if the cloudfront distribution is in state "update in progress".

**Comment by der-eismann** [comment]
@wdalmut Do you think you can implement the change?

**Comment by wdalmut** [comment]
> @wdalmut Do you think you can implement the change?

yes i want to. i use this project and i like it very much, in addition i really and need that fix (actually i have built my own release).

I just strugle to understand how to implement it because i don't have much time in this months...

**Comment by der-eismann** [comment]
@svenwltr I just gave it a try, the problem is that disabling the distribution takes a while and when it is the only resource left it fails:
```
Do you really want to nuke these resources on the account with the ID xxxxxxxx and the alias 'test'?
Do you want to continue? Enter account alias to continue.
> test

global - CloudFrontDistributionDeployment - E2SCK7OH4FPF3J - triggered remove
global - CloudFrontDistribution - E2SCK7OH4FPF3J - failed

Removal requested: 1 waiting, 1 failed, 114 skipped, 0 finished

global - CloudFrontDistributionDeployment - E2SCK7OH4FPF3J - waiting
global - CloudFrontDistribution - E2SCK7OH4FPF3J - failed

Removal requested: 1 waiting, 1 failed, 114 skipped, 0 finished

(repeats 23 times)

global - CloudFrontDistributionDeployment - E2SCK7OH4FPF3J - removed
global - CloudFrontDistribution - E2SCK7OH4FPF3J - failed

Removal requested: 0 waiting, 1 failed, 114 skipped, 1 finished

global - CloudFrontDistribution - E2SCK7OH4FPF3J - failed

Removal requested: 0 waiting, 1 failed, 114 skipped, 1 finished

global - CloudFrontDistribution - E2SCK7OH4FPF3J - failed

Removal requested: 0 waiting, 1 failed, 114 skipped, 1 finished

ERRO[0185] There are resources in failed state, but none are ready for deletion, anymore. 

global - CloudFrontDistribution - E2SCK7OH4FPF3J - failed
ERRO[0185] CloudFront Distribution E2SCK7OH4FPF3J update is still In Progress 
Error: failed
```

I'm not really sure how to fix this, apart from using the blocking call. A waiting state would be more consistent than `failed`, but I don't see a way to do that without changing the queue code.

**Comment by svenwltr** [comment]
Some ideas:
* Split resources, so we have one resource for the state and one for the actual distribution.
* Somehow introduce an error type that indicates that this resource needs to be retried.

Having a block call means that *aws-nuke* does nothing while waiting, which would slow down the whole nuke operation. This might not be bad for a single resource, but when we start with it here, than others will follow. We should be consistent with the workflow.

**Comment by der-eismann** [comment]
> * Split resources, so we have one resource for the state and one for the actual distribution.

This is actually what we do already. We have a separate `CloudFrontDistributionDeployment` resource that [disables the distribution](https://github.com/rebuy-de/aws-nuke/blob/main/resources/cloudfront-distributiondeployments.go#L71). Actually I just nuked twice with the current code and it succeeded:

```
global - CloudFrontDistribution - E2OJCF6O53KIP0 - failed
global - CloudFrontDistributionDeployment - E2OJCF6O53KIP0 - waiting

Removal requested: 1 waiting, 1 failed, 114 skipped, 0 finished

(repeats 26x)

global - CloudFrontDistribution - E2OJCF6O53KIP0 - removed
global - CloudFrontDistributionDeployment - E2OJCF6O53KIP0 - removed

Removal requested: 0 waiting, 0 failed, 114 skipped, 2 finished
```
My guess is that the users filter only for the `CloudFrontDistribution` resource and that's why it fails. To be fair, it is a bit confusing.

@wdalmut Can you post your nuke config?

**Comment by wdalmut** [comment]
@der-eismann here my example configuration:

```yaml
regions:
- eu-west-1
- eu-central-1
- us-east-1
- global

account-blacklist:
- "999999999999" # production

accounts:
  "123456789012":
    filters:
      IAMSAMLProvider:
      - arn:aws:iam::123456789012:saml-provider/AWSSSO_123456789012_DO_NOT_DELETE
      IAMRole:
      - AWSReservedSSO_AdministratorAccess_deadbeef
      - OurAdminRole
      - AWSCloudFormationStackSetExecutionRole
      Route53HostedZone:
      - /hostedzone/SOMETHINGROUTE53 (domain.name.tld.)
      IAMRolePolicy:
      - OurAdminRole -> AdministratorAccess
      IAMRolePolicyAttachment:
      - AWSReservedSSO_AdministratorAccess_deadbeef -> AdministratorAccess
      - AWSServiceRoleForSSO -> AWSSSOServiceRolePolicy
      - AWSCloudFormationStackSetExecutionRole -> AdministratorAccess
      CloudFormationStack:
      - dns
      - stack-set
```

We currently use this tool to drop everything in the account after our tests.

**Comment by der-eismann** [comment]
Okay, it's only now that I see that you have a completely different problem, when trying to disabling the distribution you got an
```
IllegalUpdate: You cannot update the specified distribution using this API version because it is associated with a cache policy.
```
To be honest I can't reproduce this. I created a CF distribution with a custom cache policy, it's nuking fine. Does your distribution use any special features? Can you try the latest master code? Maybe it was resolved with an SDK update.

**Comment by wdalmut** [comment]
@der-eismann of course i can i will try to update with your latest build and create a new cloudfront distribution on top of a bucket and another custom origin and test the account nuke. I try to test this in these days. i let you know

**Comment by wdalmut** [comment]
I tried with the latest version but i still get the error

```
global - CloudFrontDistribution - CFDISTRIBUTIONID - failed
global - CloudFrontDistributionDeployment - CFDISTRIBUTIONID - failed

Removal requested: 0 waiting, 2 failed, 143 skipped, 9 finished

global - CloudFrontDistribution - CFDISTRIBUTIONID - failed
global - CloudFrontDistributionDeployment - CFDISTRIBUTIONID - failed

Removal requested: 0 waiting, 2 failed, 143 skipped, 9 finished

ERRO[0064] There are resources in failed state, but none are ready for deletion, anymore. 

global - CloudFrontDistribution - CFDISTRIBUTIONID - failed
ERRO[0064] DistributionNotDisabled: The distribution you are trying to delete has not been disabled.
        status code: 409, request id: 57acde7f-9af5-47ea-9ef7-504a6f7ba87b 
global - CloudFrontDistributionDeployment - CFDISTRIBUTIONID - failed
ERRO[0064] IllegalUpdate: You cannot update the specified distribution using this API version because it is associated with a cache policy.
        status code: 400, request id: 97ab830e-f054-409e-b18d-bb6381ce229f 
Error: failed
```

i just created an s3 bucket and a CloudFront distribution. The CF Distribution is composed by  also a custom origin for example www.example.org and a custom behavior that use path routing to the custom origin.

The CF distribution is never updated to disabled and the tool goes in error quite immediately

**Comment by hicklemon** [comment]
Another thing that would help here is to also remove any Lambda@Edge behaviors, and possibly any CloudFormation functions (which are different from Lambdas).

**Comment by ekristen** [comment]
If this is still an issue please open an issue over on the new fork https://github.com/ekristen/aws-nuke

If you have a chance, please check it out and let us know if you run into an issues by opening an issue over on the fork.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Pull request closed without merging**
