### PR TITLE
Add support for ECS capacity providers

### PR DESCRIPTION
**Pull request by Octogonapus**
This PR adds support for ECS capacity providers.

I'm not sure how to test this. I didn't notice tests in this pkg. I could try running it on my own resources?

### CODE REVIEW

**Comment by der-eismann** [comment]
Hey @Octogonapus, thanks for your submission!

> I could try running it on my own resources?

That would be the ideal case - I assume you created this PR because you want to delete something. Trying out if it works is the best way. We don't really have tests for that.

**Comment by Octogonapus** [comment]
I ran this on my own account. Found one problem related to removing reserved capacity providers and pushed a fix for that.

There is another problem, similar to #877. Capacity providers are associated with clusters and cannot be deleted without first being disassociated from those clusters. If you are deleting the cluster as well, simply running aws-nuke twice would work around this, but I think that some explicit ordering between these two steps is desirable.

**Comment by Octogonapus** [comment]
Ok, if aws-nuke doesn't want to implement any kind of dependency management, then this is RTM.

**Comment by bjoernhaeuser** [comment]
Sorry for coming back to this to late, not sure if this is now provided by the cloud-control APIs?

**Comment by Octogonapus** [comment]
I had a look at the cloud control stuff, but I don't understand it. If aws-nuke now supports deleting ECS capacity providers, this can be closed.

**Comment by ekristen** [comment]
@Octogonapus this is going to be implemented via https://github.com/ekristen/aws-nuke/pull/320 on what is now the active managed fork of aws-nuke as such I'm closing this PR.

----

Please see the copy of the notice from the README about the deprecation of this project. Sven was kind enough to grant me access to help triage and close issues and pull requests that have already been addressed in the actively maintained fork. Some additional information is located in the [welcome issue](https://github.com/ekristen/aws-nuke/issues/276) for more information. 

> [!CAUTION]
> This repository for aws-nuke is no longer being actively maintained. We recommend users to switch to the actively maintained fork of this project at [ekristen/aws-nuke](https://github.com/ekristen/aws-nuke).
> We appreciate all the support and contributions we've received throughout the life of this project. We believe that the fork will continue to provide the functionality and support that you have come to expect from aws-nuke.
> Please note that this deprecation means we will not be addressing issues, accepting pull requests, or making future releases from this repository.
> Thank you for your understanding and support.

**Pull request closed without merging**
