### PR TITLE
Proposed fix for some of the errors around new services

### PR DESCRIPTION
**Pull request by tomvachon**
This might help #112 and #63 

Its not the most "elegant" solution but considering we can't even get a response from AWS which says ServiceUnsupported or the like, it might be all we can.  The only alternative I can think of is making a mapping of all services to all endpoints which will get messy to maintain.

### CODE REVIEW

**Comment by svenwltr** [comment]
The endpoints are already [maintained by the SDK](https://docs.aws.amazon.com/sdk-for-go/api/aws/endpoints/). I added a validation check before the actual request get sent.

What do you think?

(I actually didn't want to push into your branch, but it happened)

**Comment by tomvachon** [comment]
That seems reasonable, it may cause more updates in the long run of the SDK.  Does the v2 SDK do it as well?

**Comment by svenwltr** [comment]
It does: https://godoc.org/github.com/aws/aws-sdk-go-v2/aws/endpoints

**Comment by svenwltr** [comment]
@rebuy-de/prp-aws-nuke Please review.

**Comment by svenwltr** [comment]
Unfortunately this doesn't cover all cases. For example Lighsail is available in all regions, but the Lighsail domain isn't:

```
ERRO[0004] Listing with LightsailDomain failed. Please report this to https://github.com/rebuy-de/aws-nuke/issues/new.
    !!! InvalidInputException: Domain-related APIs are only available in the us-east-1 Region. Please set your Region configuration to us-east-1 to create, view, or edit these resources.
    !!! 	status code: 400, request id: cf5a1f23-26a1-11e8-b93c-77bf2f94ebab
```

**Pull request merged**
